### ISSUE TITLE
Class App\Sso\Server does not exist.

### ISSUE THREAD

**Issue by visualNext** [codeedu/laravel-sso#1]
I have two laravel project (https://aaa.localhost and https://bbb.localhost)

In https://aaa.localhost:
config/sso.php
```
'type' => 'server',
```
In https://bbb.localhost:
config/sso.php
```
'sso_server' => 'https://aaa.localhost',
'sso_broker_id' => env('SSO_BROKER_ID'),
'sso_broker_secret' => env('SSO_BROKER_SECRET'),
'server_prefix' => env('SSO_SERVER_PREFIX', '/'),
'type' => env('SSO_TYPE', 'broker'),
'log_erros' => env('APP_DEBUG', false),
```
But https://aaa.localhost have the error message "Class App\Sso\Server does not exist."

**Comment by argentinaluiz** [comment]
Could you share a print screen of error?

**Comment by visualNext** [comment]
https://aaa.localhost print screen of error
![{EA0A6E49-BE4E-4556-B4F9-DAF926E842A7}_20191121104929](https://user-images.githubusercontent.com/52145509/69299906-ba3f9b80-0c4c-11ea-9ccf-ed67a3bfb4bd.jpg)

**Comment by visualNext** [comment]
https://aaa.localhost and https://bbb.localhost follow the steps in readme to install.
```
composer require codeedu/laravel-sso
```
```
php artisan vendor:publish --provider="CodeEdu\LaravelSso\SSOServiceProvider"
```
Add CodeEdu\LaravelSso\Middleware\AttachBroker in routeMiddleware in Kernel.php.

config/auth.php in https://bbb.localhost:
```
'sso' => [
    'driver' => 'sso',
    'model' => \App\User::class
]
```
Is there a missing step?

**Comment by argentinaluiz** [comment]
One step left, I updated **the server configuration** in readme.md.

Thanks for feedback.

**Comment by visualNext** [comment]
I add the step to https://aaa.localhost, but have the new error message.
```
{"error":"Unknown command"}
```

**Comment by visualNext** [comment]
I try to log in https://bbb.localhost, but it use https://bbb.localhost user db data not https://aaa.localhost. I have another project ccc, and add sso broker. When I log in bbb, ccc is't signed. What code and step need to add?
